### ISSUE TITLE
Ready for a official PR?

### ISSUE THREAD

**Issue by lars18th** [yousong/waller#1]
Hi @yousong ,

Your packages seem to be interesting. Specially the `pservice` is very lightweight, so please create a PR in the official packages repository: https://github.com/openwrt/packages

Thank you!

**Comment by yousong** [comment]
Thank you for the remainder.  Will prepare a pull request in the following days and update here.  Stay tuned

**Comment by yousong** [comment]
Created a pull request openwrt/packages#9644 .  Let's direct further comments there ;)
